// let top150EnglishWords = [
//   "a",
//   "about",
//   "after",
//   "again",
//   "all",
//   "also",
//   "an",
//   "and",
//   "another",
//   "any",
//   "are",
//   "around",
//   "as",
//   "at",
//   "away",
//   "back",
//   "be",
//   "because",
//   "been",
//   "before",
//   "but",
//   "by",
//   "called",
//   "came",
//   "can",
//   "come",
//   "could",
//   "day",
//   "did",
//   "different",
//   "do",
//   "does",
//   "down",
//   "each",
//   "even",
//   "find",
//   "first",
//   "for",
//   "from",
//   "get",
//   "go",
//   "good",
//   "had",
//   "has",
//   "have",
//   "he",
//   "help",
//   "her",
//   "here",
//   "him",
//   "his",
//   "how",
//   "I",
//   "if",
//   "in",
//   "into",
//   "is",
//   "it",
//   "its",
//   "just",
//   "know",
//   "like",
//   "little",
//   "long",
//   "look",
//   "made",
//   "make",
//   "man",
//   "many",
//   "may",
//   "me",
//   "more",
//   "most",
//   "much",
//   "must",
//   "my",
//   "new",
//   "no",
//   "not",
//   "now",
//   "number",
//   "of",
//   "off",
//   "old",
//   "on",
//   "one",
//   "only",
//   "or",
//   "other",
//   "our",
//   "out",
//   "over",
//   "part",
//   "people",
//   "place",
//   "put",
//   "right",
//   "said",
//   "same",
//   "see",
//   "she",
//   "so",
//   "some",
//   "such",
//   "take",
//   "than",
//   "that",
//   "the",
//   "their",
//   "them",
//   "then",
//   "there",
//   "these",
//   "they",
//   "things",
//   "think",
//   "this",
//   "three",
//   "through",
//   "time",
//   "to",
//   "too",
//   "two",
//   "up",
//   "use",
//   "used",
//   "very",
//   "was",
//   "water",
//   "way",
//   "we",
//   "well",
//   "went",
//   "were",
//   "what",
//   "when",
//   "where",
//   "which",
//   "who",
//   "why",
//   "will",
//   "with",
//   "word",
//   "words",
//   "work",
//   "would",
//   "write",
//   "years",
//   "you",
//   "your",
// ];

//It will console log every index, followed by the array item at that index.
//The first consolee log is: 0 'a'
//The last one is: 149 'your'
// for (let i = 0; i < top150EnglishWords.length; i++) {
//   console.log(i, top150EnglishWords[i]);
// }

//Same but in reverse
// for (let i = 149; i >= 0; i--) {
//   console.log(i, top150EnglishWords[i]);
// }

// //Multiple ways to do the same thing
// for (let i = top150EnglishWords.length - 1; i >= 0; i--) {
//   console.log(i, top150EnglishWords[i]);
// }

// const people = ["Scooby", "Velma", "Daphne", "Shaggy", "Fred"];

// for (let i = 0; i < people.length; i++) {
//   console.log(people[i].toUpperCase());
// }
